### ISSUE TITLE
Populate WhatDoTheyKnow IDs

### ISSUE THREAD

**Issue by JackGilmore** [OpenDataScotland/the_od_bods#71]
![image](https://user-images.githubusercontent.com/46202639/168259557-0737f984-0c8e-4e30-a878-278a470f7432.png)

We added a new field to orgs for WhatDoTheyKnow IDs so we can link to to their list of FOI requests published on https://www.whatdotheyknow.com/. However, not all orgs have this value populated. This could be a good exercise for someone to go through all the orgs in opendata.scot and populate them accordingly.

To populate, the user needs to find the relevant organisation on WDTK (e.g. https://www.whatdotheyknow.com/body/aberdeen_city_council for Aberdeen City Council), take the ID which is the text after `https://www.whatdotheyknow.com/body/` (i.e. aberdeen_city_council) and copy that into the WhatDoTheyKnow organization ID field for the org.

You can see what organisations are missing their ID by checking the WDTK column on our [platform health report](https://opendata.scot/analytics/platform-health/)

**Comment by watty62** [comment]
I've added all WDTK IDs for entities which exist in [WDTK](https://www.whatdotheyknow.com). 

There are some glaring omissions. eg Business Gateway, but this might just be because no-one has yet made a request via WDTK. 

Others (eg Code The City) are not public bodies. Some are not clear (see [UBDC](https://www.ubdc.ac.uk/about-ubdc/who-we-are/advisory-group/).) 

I think that this can be closed for now. 

Ian
